export const faqKeys = [
  "faq_what_is_coop",
  "faq_purpose",
  "faq_how_to_start",
  "faq_rewards_distribution",
  "faq_contribution_types",
  "faq_voting",
  "faq_voter_eligibility",
  "faq_tit_for_tat_voting",
  "faq_liquid_rewards",
  "faq_lock_other_tokens",
  "faq_deposit_amount",
  "faq_unlock_tokens",
  "faq_prerequisites",
  "faq_security_and_rules",
  "faq_initial_supply",
  "faq_token_minting",
  "faq_price_protection",
  "faq_inflation",
  "faq_referrals",
  "faq_governance",
  "faq_team",
  "faq_why_participate",
] as const;
